program: main.py
name: "Sweep Example (w/ FM)"
project: 'book-rating-prediction'
method: bayes
metric:
    goal: minimize
    name: 'Valid RMSE'


parameters:
    n_estimators:                       # 트리 모델 학습 에폭 수
        min: 100
        max: 1000
    max_depth:                          # 트리 모델의 최대 트리 깊이
        min: 3
        max: 15
    learning_rate:                      # 트리 모델의 학습률
        min: 0.01
        max: 0.3


command:
    - -c config/config_baseline.yaml
    - -m CatBoost
    - -w True
    - -r FM_baseline